// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.29.3
// source: proto/user_task.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          uint32                 `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`                                         // sender id
	PublicKeyInfo []byte                 `protobuf:"bytes,2,opt,name=public_key_info,json=publicKeyInfo,proto3" json:"public_key_info,omitempty"` // public key
	Msg           []byte                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`                                            // message
	Protocol      uint32                 `protobuf:"varint,4,opt,name=protocol,proto3" json:"protocol,omitempty"`                                 // 1: ECDSA, 2: Schnorr
	Curve         uint32                 `protobuf:"varint,5,opt,name=curve,proto3" json:"curve,omitempty"`                                       // 1: ED25519, 2: SECP256K1, 3: SECP256R1, 4: P256
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_proto_user_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_proto_user_task_proto_rawDescGZIP(), []int{0}
}

func (x *SignRequest) GetFrom() uint32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *SignRequest) GetPublicKeyInfo() []byte {
	if x != nil {
		return x.PublicKeyInfo
	}
	return nil
}

func (x *SignRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *SignRequest) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *SignRequest) GetCurve() uint32 {
	if x != nil {
		return x.Curve
	}
	return 0
}

type SignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"` // success flag
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`      // error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignResponse) Reset() {
	*x = SignResponse{}
	mi := &file_proto_user_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignResponse) ProtoMessage() {}

func (x *SignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_user_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignResponse.ProtoReflect.Descriptor instead.
func (*SignResponse) Descriptor() ([]byte, []int) {
	return file_proto_user_task_proto_rawDescGZIP(), []int{1}
}

func (x *SignResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_user_task_proto protoreflect.FileDescriptor

const file_proto_user_task_proto_rawDesc = "" +
	"\n" +
	"\x15proto/user_task.proto\"\x8d\x01\n" +
	"\vSignRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\rR\x04from\x12&\n" +
	"\x0fpublic_key_info\x18\x02 \x01(\fR\rpublicKeyInfo\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\fR\x03msg\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\rR\bprotocol\x12\x14\n" +
	"\x05curve\x18\x05 \x01(\rR\x05curve\"\\\n" +
	"\fSignResponse\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error21\n" +
	"\bUserTask\x12%\n" +
	"\x04Sign\x12\f.SignRequest\x1a\r.SignResponse\"\x00B\tZ\a./protob\x06proto3"

var (
	file_proto_user_task_proto_rawDescOnce sync.Once
	file_proto_user_task_proto_rawDescData []byte
)

func file_proto_user_task_proto_rawDescGZIP() []byte {
	file_proto_user_task_proto_rawDescOnce.Do(func() {
		file_proto_user_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_user_task_proto_rawDesc), len(file_proto_user_task_proto_rawDesc)))
	})
	return file_proto_user_task_proto_rawDescData
}

var file_proto_user_task_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_user_task_proto_goTypes = []any{
	(*SignRequest)(nil),  // 0: SignRequest
	(*SignResponse)(nil), // 1: SignResponse
}
var file_proto_user_task_proto_depIdxs = []int32{
	0, // 0: UserTask.Sign:input_type -> SignRequest
	1, // 1: UserTask.Sign:output_type -> SignResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_user_task_proto_init() }
func file_proto_user_task_proto_init() {
	if File_proto_user_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_user_task_proto_rawDesc), len(file_proto_user_task_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_user_task_proto_goTypes,
		DependencyIndexes: file_proto_user_task_proto_depIdxs,
		MessageInfos:      file_proto_user_task_proto_msgTypes,
	}.Build()
	File_proto_user_task_proto = out.File
	file_proto_user_task_proto_goTypes = nil
	file_proto_user_task_proto_depIdxs = nil
}
