// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/user_task.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserTask_Sign_FullMethodName = "/UserTask/Sign"
)

// UserTaskClient is the client API for UserTask service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserTask service for user operations in the key management system.
type UserTaskClient interface {
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
}

type userTaskClient struct {
	cc grpc.ClientConnInterface
}

func NewUserTaskClient(cc grpc.ClientConnInterface) UserTaskClient {
	return &userTaskClient{cc}
}

func (c *userTaskClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, UserTask_Sign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserTaskServer is the server API for UserTask service.
// All implementations must embed UnimplementedUserTaskServer
// for forward compatibility.
//
// UserTask service for user operations in the key management system.
type UserTaskServer interface {
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	mustEmbedUnimplementedUserTaskServer()
}

// UnimplementedUserTaskServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserTaskServer struct{}

func (UnimplementedUserTaskServer) Sign(context.Context, *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (UnimplementedUserTaskServer) mustEmbedUnimplementedUserTaskServer() {}
func (UnimplementedUserTaskServer) testEmbeddedByValue()                  {}

// UnsafeUserTaskServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserTaskServer will
// result in compilation errors.
type UnsafeUserTaskServer interface {
	mustEmbedUnimplementedUserTaskServer()
}

func RegisterUserTaskServer(s grpc.ServiceRegistrar, srv UserTaskServer) {
	// If the following call pancis, it indicates UnimplementedUserTaskServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserTask_ServiceDesc, srv)
}

func _UserTask_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserTaskServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserTask_Sign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserTaskServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserTask_ServiceDesc is the grpc.ServiceDesc for UserTask service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserTask_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserTask",
	HandlerType: (*UserTaskServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _UserTask_Sign_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/user_task.proto",
}
